const BOOKS = [
  {
    title: "Ready Player One",
    authorFirst: "Ernest",
    authorLast: "Cline",
    length: 386,
    spine: "./images/rpospine.jpg",
    cover: "./images/rpocover.jpg",
  },
  {
    title: "Ready Player Two",
    authorFirst: "Ernest",
    authorLast: "Cline",
    length: 592,
    spine: "./images/rptspine.jpg",
    cover: "./images/rptcover.jpg",
  },
  {
    title: "One Piece",
    authorFirst: "Eiichiro",
    authorLast: "Oda",
    length: 20083,
    spine: "./images/opspine.png",
    cover: "./images/opcover.jpg",
  },
  {
    title: "Harry Potter and the Sorcerer's Stone",
    authorFirst: "J.K.",
    authorLast: "Rowling",
    length: 309,
    spine: "./images/hp1spine.jpg",
    cover: "./images/hp1cover.jpg",
  },
  {
    title: "Harry Potter and the Chamber of Secrets",
    authorFirst: "J.K.",
    authorLast: "Rowling",
    length: 341,
    spine: "./images/hp2spine.jpeg",
    cover: "./images/hp2cover.jpg",
  },
  {
    title: "Harry Potter and the Prisoner of Azkaban",
    authorFirst: "J.K.",
    authorLast: "Rowling",
    length: 435,
    spine: "./images/hp3spine.jpeg",
    cover: "./images/hp3cover.jpg",
  },
  {
    title: "Harry Potter and the Goblet of Fire",
    authorFirst: "J.K.",
    authorLast: "Rowling",
    length: 734,
    spine: "./images/hp4spine.jpeg",
    cover: "./images/hp4cover.jpg",
  },
  {
    title: "Harry Potter and the Order of the Phoenix",
    authorFirst: "J.K.",
    authorLast: "Rowling",
    length: 870,
    spine: "./images/hp5spine.jpeg",
    cover: "./images/hp5cover.jpg",
  },
  {
    title: "Harry Potter and the Half Blood Prince",
    authorFirst: "J.K.",
    authorLast: "Rowling",
    length: 652,
    spine: "./images/hp6spine.jpeg",
    cover: "./images/hp6cover.jpg",
  },
  {
    title: "Harry Potter and the Deathly Hallows",
    authorFirst: "J.K.",
    authorLast: "Rowling",
    length: 759,
    spine: "./images/hp7spine.jpeg",
    cover: "./images/hp7cover.jpg",
  },
];

export default BOOKS;
